In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.tensor([5.5, 3])
print(x)


tensor([5.5000, 3.0000])


In [5]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.rand_like(x, dtype=torch.float)
print(x)


tensor([[0.7003, 0.8549, 0.2075],
        [0.8911, 0.2285, 0.7680],
        [0.3448, 0.4893, 0.2197],
        [0.7751, 0.2262, 0.5072],
        [0.4460, 0.5606, 0.2301]])


In [8]:
print(x.size())


torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)


tensor([[0.8446, 1.8321, 1.0175],
        [1.2351, 0.9322, 0.9685],
        [0.3602, 0.9524, 0.2435],
        [0.8510, 0.7823, 0.6790],
        [0.8927, 0.7267, 0.6613]])


In [10]:
print(torch.add(x, y))


tensor([[0.8446, 1.8321, 1.0175],
        [1.2351, 0.9322, 0.9685],
        [0.3602, 0.9524, 0.2435],
        [0.8510, 0.7823, 0.6790],
        [0.8927, 0.7267, 0.6613]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)


tensor([[0.8446, 1.8321, 1.0175],
        [1.2351, 0.9322, 0.9685],
        [0.3602, 0.9524, 0.2435],
        [0.8510, 0.7823, 0.6790],
        [0.8927, 0.7267, 0.6613]])


In [12]:
y.add_(x)
print(y)


tensor([[0.8446, 1.8321, 1.0175],
        [1.2351, 0.9322, 0.9685],
        [0.3602, 0.9524, 0.2435],
        [0.8510, 0.7823, 0.6790],
        [0.8927, 0.7267, 0.6613]])


In [13]:
print(x[:, 1])


tensor([0.8549, 0.2285, 0.4893, 0.2262, 0.5606])


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1)
print(x)
print(x.item())


tensor([-1.7258])
-1.7258377075195312


In [16]:
a = torch.ones(5)
print(a)


tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)


[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)


tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [21]:
torch.cuda.is_available()


False